<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>try..catch</title>
    <link rel="stylesheet" href="../global.css">
</head>

<body>
    <header>
        <a href="../index.html" class="back_button"></a>
    </header>
    <main>
        <h1>try..catch</h1>
        <section>
            <article>
                <p>
                    Мы пытаемся вывести в консоль необъявленную
                    переменную. Из-за этой ошибки выполнится блок
                    catch и выведет своё сообщение в консоль
                </p>
                <pre>
    try {
        console.log(notExist)
    } catch {
        console.log('где то ошибка')
    }                    
                </pre>
            </article>
            <article>
                <p>
                    Блок catch принимает в себя объект ошибки, у него есть
                    свойства, которыми мы можем воспользоваться
                </p>
                <pre>
    try {
        console.log(notExist)
    } catch (err) {
        console.log(err.name)     // ReferenceError
        console.log(err.message)  // notExist is not defined
        console.log(err.stack)    // ReferenceError: notExist is not defined at script.js:26:17
    
    }                                       
                </pre>
            </article>
            <article>
                <p>
                    throw позволяет сразу выбросить ошибку и перейти
                    в блок catch с переданным объектом ошибки
                </p>
                <pre>
    try {
        const data = JSON.parse('{"name": "User"}')
        if (!data.id) {
            throw new Error('simple error')
        }
    } catch (err) {
        console.dir(err.name) //Error
        console.dir(err.message) //'simple error'
    }

    let error1 = new Error('1');
    let error2 = new SyntaxError('2');
    let error3 = new ReferenceError('3');
    Данный синтаксис позволяет генерировать собственные ошибки.
    error1.name -> Error
    error1.message -> '1'
    error2.name -> SyntaxError
    error2.message -> '2'
    error2.name -> ReferenceError
    error3.message -> '3'
                </pre>
            </article>
            <article>
                <h3>finally</h3>
                <p>
                    finally выполняет свой блок кода в любом случае,
                    независимо от ошибки. Это полезно в тех случаях,
                    когда процессы запущенные в try должны быть
                    завершены даже при возникновении неполадок
                </p>
                <pre>
    try {
        console.log(notExist)
    } catch {
        console.log('где то ошибка')
    }  finally {
        console.log('в любом случае')
    }                    
                </pre>
            </article>
            <article>
                <h3>onerror</h3>
                <p>
                    Глобальный объект window предоставляет свой метод обработки
                    ошибок onerror. Он будет вызван в случае ошибки
                </p>
                <pre>
    onerror = (message, url, line, col, error) => {
        alert('error')
    }                                        
                </pre>
            </article>
        </section>
        <hr>
        <section>
            <h2>fetch</h2>
            <p>
                Для сетевых запросов из JavaScript есть
                широко известный термин «AJAX» (аббревиатура от Asynchronous
                JavaScript And XML). XML мы использовать не обязаны,
                просто термин старый, поэтому в нём есть это слово.
                Возможно, вы его уже где-то слышали.
            </p>
            <p>
                Есть несколько способов делать сетевые
                запросы и получать информацию с сервера.
            </p>
            <p>
                Метод fetch() — современный и очень мощный,
                поэтому начнём с него. Он не поддерживается
                старыми (можно использовать полифил),
                но поддерживается всеми современными браузерами.
            </p>
            <pre>
    fetch('https://jsonplaceholder.typicode.com/albums')
    .then(res => {
        if (res.status === 200) return res.json()
        else throw new Error('request crashed')
    })
    .then(data => console.log(data))
    .catch(err => {
        console.error(err.message);
    })            
            </pre>
        </section>
        <section id="root"></section>
        <section id="usersContainer"></section>
    </main>
    <footer>
        <h2>HW</h2>
        <a href="./hw/alexandr/index.html" target="_blank">Александр</a>
        <a href="./hw/andrey/index.html" target="_blank">Андрей</a>
        <a href="./hw/artyom/index.html" target="_blank">Артём</a>
        <a href="./hw/choigan/index.html" target="_blank">Чойган</a>
        <a href="./hw/varkentin/index.html" target="_blank">Юлия</a>
    </footer>
    <script src="./script.js"></script>
</body>

</html>